### ISSUE TITLE
Specify ports for TCP SYN discovery

### ISSUE THREAD

**Issue by kcning** [postmodern/ruby-nmap#47]
with CLI we can specify which ports nmap should use TCP SYN for ping scan. For example:
```
nmap -sn -PS1-20 scanme.nmap.org
```
How can we specify this with the gem? I tried some options but they don't seem to work. Here is the code:
```
Nmap::Program.scan do |nmap|
  nmap.ping = true
  nmap.syn_discovery = true

  # none of those worked
  # nmap.syn_discovery = '1-20'
  # nmap.syn_discovery = 1..20
  # nmap.syn_discovery = (1..20).to_a

  nmap.targets = 'scanme.nmap.org
end
```

**Comment by postmodern** [comment]
Sorry for not responding to this issue sooner, but it appears I fixed this in 83b79528bac96d7ba60ea07d722fccbc10f17114 which was released in 0.9.3 (2018-05-01).
