### ISSUE TITLE
sophsec.com has expired

### ISSUE THREAD

**Issue by noraj** [postmodern/ruby-nmap#53]
http://www.sophsec.com/ domain is for sale

**Comment by blacklist-arcc** [comment]
![image](https://user-images.githubusercontent.com/26464774/120717281-9149c900-c4c7-11eb-8baa-e3165c238181.png)

**Comment by postmodern** [comment]
I ended up moving this project over to my account. Doubtful we'll be able to get the domain back from HugeDomains who are holding it ransom for $3.8k...
